### ISSUE TITLE
Using Scatter3D makes matplotlib throw exception

### ISSUE THREAD

**Issue by jenssss** [pyviz/holoviews#3742]
When running the example code from http://holoviews.org/reference/elements/matplotlib/Scatter3D.html#matplotlib-gallery-scatter3d as a stand alone file

```
import numpy as np
import holoviews as hv
from pathlib import Path
backend = "matplotlib"
outfile = "holoviews_scatter3D"
hv.extension(backend)

y, x = np.mgrid[-5:5, -5:5] * 0.1
heights = np.sin(x**2+y**2)
scat = hv.Scatter3D((x.flat, y.flat, heights.flat)).opts(
    hv.opts.Scatter3D(azimuth=40, elevation=20, color='z', s=50, cmap='fire'))


renderer = hv.renderer(backend)
renderer.save(scat, outfile)
```

I get the following exception thrown (in addition to a bunch of deprecation warnings)
```
Traceback (most recent call last):
  File "scatter3D_test.py", line 15, in <module>
    renderer.save(scat, outfile)
  File "/home/me/test_new_python_stuff/lib/python3.6/site-packages/holoviews/plotting/renderer.py", line 545, in save
    plot = self_or_cls.get_plot(obj)
  File "/home/me/test_new_python_stuff/lib/python3.6/site-packages/holoviews/plotting/renderer.py", line 207, in get_plot
    plot.update(init_key)
  File "/home/me/test_new_python_stuff/lib/python3.6/site-packages/holoviews/plotting/mpl/plot.py", line 243, in update
    return self.initialize_plot()
  File "/home/me/test_new_python_stuff/lib/python3.6/site-packages/holoviews/plotting/mpl/plot.py", line 48, in wrapper
    return f(self, *args, **kwargs)
  File "/home/me/test_new_python_stuff/lib/python3.6/site-packages/holoviews/plotting/mpl/element.py", line 512, in initialize_plot
    **axis_kwargs)
  File "/home/me/test_new_python_stuff/lib/python3.6/site-packages/holoviews/plotting/mpl/chart3d.py", line 87, in _finalize_axis
    return super(Plot3D, self)._finalize_axis(key, **kwargs)
  File "/home/me/test_new_python_stuff/lib/python3.6/site-packages/holoviews/plotting/mpl/element.py", line 187, in _finalize_axis
    self._set_aspect(axis, self.aspect)
  File "/home/me/test_new_python_stuff/lib/python3.6/site-packages/holoviews/plotting/mpl/element.py", line 310, in _set_aspect
    axes.set_aspect(data_ratio)
  File "/home/me/test_new_python_stuff/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1281, in set_aspect
    'It is not currently possible to manually set the aspect '
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes
```

I'm using holoviews version 1.12.3 and matplotlib version 3.1.0

I also tried running the example in a notebook, which gave the following error trace
<details><summary>Notebook error </summary>
<p>

```

:Scatter3D   [x,y,z]

Error in callback <function install_repl_displayhook.<locals>.post_execute at 0x7fa8b47e08c8> (for post_execute):

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/matplotlib/pyplot.py in post_execute()
    107             def post_execute():
    108                 if matplotlib.is_interactive():
--> 109                     draw_all()
    110 
    111             # IPython >= 2

~/.local/lib/python3.6/site-packages/matplotlib/_pylab_helpers.py in draw_all(cls, force)
    126         for f_mgr in cls.get_all_fig_managers():
    127             if force or f_mgr.canvas.figure.stale:
--> 128                 f_mgr.canvas.draw_idle()
    129 
    130 atexit.register(Gcf.destroy_all)

~/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py in draw_idle(self, *args, **kwargs)
   1905         if not self._is_idle_drawing:
   1906             with self._idle_draw_cntx():
-> 1907                 self.draw(*args, **kwargs)
   1908 
   1909     def draw_cursor(self, event):

~/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    386         self.renderer = self.get_renderer(cleared=True)
    387         with RendererAgg.lock:
--> 388             self.figure.draw(self.renderer)
    389             # A GUI class may be need to update a window using this draw, so
    390             # don't forget to call the superclass.

~/.local/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

~/.local/lib/python3.6/site-packages/matplotlib/figure.py in draw(self, renderer)
   1707             self.patch.draw(renderer)
   1708             mimage._draw_list_compositing_images(
-> 1709                 renderer, self, artists, self.suppressComposite)
   1710 
   1711             renderer.close_group('figure')

~/.local/lib/python3.6/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    133     if not_composite or not has_images:
    134         for a in artists:
--> 135             a.draw(renderer)
    136     else:
    137         # Composite any adjacent images together

~/.local/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

~/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/axes3d.py in draw(self, renderer)
    290                 sorted(self.collections,
    291                        key=lambda col: col.do_3d_projection(renderer),
--> 292                        reverse=True)):
    293             col.zorder = zorder_offset + i
    294         for i, patch in enumerate(

~/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/axes3d.py in <lambda>(col)
    289         for i, col in enumerate(
    290                 sorted(self.collections,
--> 291                        key=lambda col: col.do_3d_projection(renderer),
    292                        reverse=True)):
    293             col.zorder = zorder_offset + i

~/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/art3d.py in do_3d_projection(self, renderer)
    543         self.set_facecolors(fcs)
    544 
--> 545         ecs = (_zalpha(self._edgecolor3d, vzs) if self._depthshade else
    546                self._edgecolor3d)
    547         ecs = mcolors.to_rgba_array(ecs, self._alpha)

~/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/art3d.py in _zalpha(colors, zs)
    845     norm = Normalize(min(zs), max(zs))
    846     sats = 1 - norm(zs) * 0.7
--> 847     rgba = np.broadcast_to(mcolors.to_rgba_array(colors), (len(zs), 4))
    848     return np.column_stack([rgba[:, :3], rgba[:, 3] * sats])
    849 

~/.local/lib/python3.6/site-packages/numpy/lib/stride_tricks.py in broadcast_to(array, shape, subok)
    180            [1, 2, 3]])
    181     """
--> 182     return _broadcast_to(array, shape, subok=subok, readonly=True)
    183 
    184 

~/.local/lib/python3.6/site-packages/numpy/lib/stride_tricks.py in _broadcast_to(array, shape, subok, readonly)
    127     it = np.nditer(
    128         (array,), flags=['multi_index', 'refs_ok', 'zerosize_ok'] + extras,
--> 129         op_flags=[op_flag], itershape=shape, order='C')
    130     with it:
    131         # never really has writebackifcopy semantics

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (0,4) and requested shape (100,4)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~/.local/lib/python3.6/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    242 
    243     if 'png' in formats:
--> 244         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    245     if 'retina' in formats or 'png2x' in formats:
    246         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~/.local/lib/python3.6/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    126 
    127     bytes_io = BytesIO()
--> 128     fig.canvas.print_figure(bytes_io, **kw)
    129     data = bytes_io.getvalue()
    130     if fmt == 'svg':

~/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2054                         orientation=orientation,
   2055                         dryrun=True,
-> 2056                         **kwargs)
   2057                     renderer = self.figure._cachedRenderer
   2058                     bbox_artists = kwargs.pop("bbox_extra_artists", None)

~/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    525 
    526         else:
--> 527             FigureCanvasAgg.draw(self)
    528             renderer = self.get_renderer()
    529             with cbook._setattr_cm(renderer, dpi=self.figure.dpi), \

~/.local/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    386         self.renderer = self.get_renderer(cleared=True)
    387         with RendererAgg.lock:
--> 388             self.figure.draw(self.renderer)
    389             # A GUI class may be need to update a window using this draw, so
    390             # don't forget to call the superclass.

~/.local/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

~/.local/lib/python3.6/site-packages/matplotlib/figure.py in draw(self, renderer)
   1707             self.patch.draw(renderer)
   1708             mimage._draw_list_compositing_images(
-> 1709                 renderer, self, artists, self.suppressComposite)
   1710 
   1711             renderer.close_group('figure')

~/.local/lib/python3.6/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    133     if not_composite or not has_images:
    134         for a in artists:
--> 135             a.draw(renderer)
    136     else:
    137         # Composite any adjacent images together

~/.local/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

~/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/axes3d.py in draw(self, renderer)
    290                 sorted(self.collections,
    291                        key=lambda col: col.do_3d_projection(renderer),
--> 292                        reverse=True)):
    293             col.zorder = zorder_offset + i
    294         for i, patch in enumerate(

~/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/axes3d.py in <lambda>(col)
    289         for i, col in enumerate(
    290                 sorted(self.collections,
--> 291                        key=lambda col: col.do_3d_projection(renderer),
    292                        reverse=True)):
    293             col.zorder = zorder_offset + i

~/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/art3d.py in do_3d_projection(self, renderer)
    543         self.set_facecolors(fcs)
    544 
--> 545         ecs = (_zalpha(self._edgecolor3d, vzs) if self._depthshade else
    546                self._edgecolor3d)
    547         ecs = mcolors.to_rgba_array(ecs, self._alpha)

~/.local/lib/python3.6/site-packages/mpl_toolkits/mplot3d/art3d.py in _zalpha(colors, zs)
    845     norm = Normalize(min(zs), max(zs))
    846     sats = 1 - norm(zs) * 0.7
--> 847     rgba = np.broadcast_to(mcolors.to_rgba_array(colors), (len(zs), 4))
    848     return np.column_stack([rgba[:, :3], rgba[:, 3] * sats])
    849 

~/.local/lib/python3.6/site-packages/numpy/lib/stride_tricks.py in broadcast_to(array, shape, subok)
    180            [1, 2, 3]])
    181     """
--> 182     return _broadcast_to(array, shape, subok=subok, readonly=True)
    183 
    184 

~/.local/lib/python3.6/site-packages/numpy/lib/stride_tricks.py in _broadcast_to(array, shape, subok, readonly)
    127     it = np.nditer(
    128         (array,), flags=['multi_index', 'refs_ok', 'zerosize_ok'] + extras,
--> 129         op_flags=[op_flag], itershape=shape, order='C')
    130     with it:
    131         # never really has writebackifcopy semantics

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (0,4) and requested shape (100,4)

<Figure size 432x432 with 1 Axes>
```

</p>
</details>

Great library btw, I really enjoy using Holoviews

**Comment by javiergcas** [comment]
I have a similar issue with the hv.Scatter3D object, but it only happens for the Matplotlib backend, and not for the Plotly backend. 

If I run the following code:
```python
import bumpy as np
import holoviews as hv
hv.extension('plotly')
a = hv.Scatter3D(np.random.rand(100,4))
a
```
Things work well. Conversely, if I run

```python 
import bumpy as np
import holoviews as hv
hv.extension('matplotlib')
a = hv.Scatter3D(np.random.rand(100,4))
a
```

Then, I get the following error:
```
Out[5]: ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/holoviews/core/dimension.py in _repr_mimebundle_(self, include, exclude)
   1292         combined and returned.
   1293         """
-> 1294         return Store.render(self)
   1295 
   1296 

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/holoviews/core/options.py in render(cls, obj)
   1364         data, metadata = {}, {}
   1365         for hook in hooks:
-> 1366             ret = hook(obj)
   1367             if ret is None:
   1368                 continue

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/holoviews/ipython/display_hooks.py in pprint_display(obj)
    279     if not ip.display_formatter.formatters['text/plain'].pprint:
    280         return None
--> 281     return display(obj, raw_output=True)
    282 
    283 

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/holoviews/ipython/display_hooks.py in display(obj, raw_output, **kwargs)
    249     elif isinstance(obj, (CompositeOverlay, ViewableElement)):
    250         with option_state(obj):
--> 251             output = element_display(obj)
    252     elif isinstance(obj, (Layout, NdLayout, AdjointLayout)):
    253         with option_state(obj):

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/holoviews/ipython/display_hooks.py in wrapped(element)
    144         try:
    145             max_frames = OutputSettings.options['max_frames']
--> 146             mimebundle = fn(element, max_frames=max_frames)
    147             if mimebundle is None:
    148                 return {}, {}

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/holoviews/ipython/display_hooks.py in element_display(element, max_frames)
    190         return None
    191 
--> 192     return render(element)
    193 
    194 

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/holoviews/ipython/display_hooks.py in render(obj, **kwargs)
     66         renderer = renderer.instance(fig='png')
     67 
---> 68     return renderer.components(obj, **kwargs)
     69 
     70 

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/holoviews/plotting/renderer.py in components(self, obj, fmt, comm, **kwargs)
    326             plot_id = plot.plot_id
    327         else:
--> 328             html, js = self._figure_data(plot, fmt, as_script=True, **kwargs)
    329             plot_id = plot.id
    330             if comm and plot.comm is not None and self.comm_msg_handler:

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/holoviews/plotting/mpl/renderer.py in _figure_data(self, plot, fmt, bbox_inches, as_script, **kwargs)
    220                 pass
    221             bytes_io = BytesIO()
--> 222             fig.canvas.print_figure(bytes_io, **kw)
    223             data = bytes_io.getvalue()
    224 

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2054                         orientation=orientation,
   2055                         dryrun=True,
-> 2056                         **kwargs)
   2057                     renderer = self.figure._cachedRenderer
   2058                     bbox_artists = kwargs.pop("bbox_extra_artists", None)

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    525 
    526         else:
--> 527             FigureCanvasAgg.draw(self)
    528             renderer = self.get_renderer()
    529             with cbook._setattr_cm(renderer, dpi=self.figure.dpi), \

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    386         self.renderer = self.get_renderer(cleared=True)
    387         with RendererAgg.lock:
--> 388             self.figure.draw(self.renderer)
    389             # A GUI class may be need to update a window using this draw, so
    390             # don't forget to call the superclass.

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/matplotlib/figure.py in draw(self, renderer)
   1707             self.patch.draw(renderer)
   1708             mimage._draw_list_compositing_images(
-> 1709                 renderer, self, artists, self.suppressComposite)
   1710 
   1711             renderer.close_group('figure')

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    133     if not_composite or not has_images:
    134         for a in artists:
--> 135             a.draw(renderer)
    136     else:
    137         # Composite any adjacent images together

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py in draw(self, renderer)
    290                 sorted(self.collections,
    291                        key=lambda col: col.do_3d_projection(renderer),
--> 292                        reverse=True)):
    293             col.zorder = zorder_offset + i
    294         for i, patch in enumerate(

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py in <lambda>(col)
    289         for i, col in enumerate(
    290                 sorted(self.collections,
--> 291                        key=lambda col: col.do_3d_projection(renderer),
    292                        reverse=True)):
    293             col.zorder = zorder_offset + i

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/mpl_toolkits/mplot3d/art3d.py in do_3d_projection(self, renderer)
    543         self.set_facecolors(fcs)
    544 
--> 545         ecs = (_zalpha(self._edgecolor3d, vzs) if self._depthshade else
    546                self._edgecolor3d)
    547         ecs = mcolors.to_rgba_array(ecs, self._alpha)

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/mpl_toolkits/mplot3d/art3d.py in _zalpha(colors, zs)
    845     norm = Normalize(min(zs), max(zs))
    846     sats = 1 - norm(zs) * 0.7
--> 847     rgba = np.broadcast_to(mcolors.to_rgba_array(colors), (len(zs), 4))
    848     return np.column_stack([rgba[:, :3], rgba[:, 3] * sats])
    849 

<__array_function__ internals> in broadcast_to(*args, **kwargs)

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/numpy/lib/stride_tricks.py in broadcast_to(array, shape, subok)
    180            [1, 2, 3]])
    181     """
--> 182     return _broadcast_to(array, shape, subok=subok, readonly=True)
    183 
    184 

/data/SFIMJGC/Apps/envs/py37_bokeh/lib/python3.7/site-packages/numpy/lib/stride_tricks.py in _broadcast_to(array, shape, subok, readonly)
    125     it = np.nditer(
    126         (array,), flags=['multi_index', 'refs_ok', 'zerosize_ok'] + extras,
--> 127         op_flags=['readonly'], itershape=shape, order='C')
    128     with it:
    129         # never really has writebackifcopy semantics

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (0,4) and requested shape (100,4)
:Scatter3D   [x,y,z]
```

As for library versions:

python = 3.7.3
numpy = 1.17.0
holoviews = 1.12.4 
matplotlib = 3.1.1
plotly = 4.0.0

Thanks a lot for your help

**Comment by philippjfr** [comment]
@jenssss The former issue should now be fixed in holoviews 1.12.4.  @javiergcas I can reproduce.
