### ISSUE TITLE
How to save data from a plot in an app

### ISSUE THREAD

**Issue by phonchi** [pyviz/holoviews#3902]
Dear developers:

I have a simple app that is similar to [this](http://holoviews.org/reference/apps/bokeh/selection_stream.html#bokeh-gallery-selection-stream). But I would like to add additional functionality to save the indices of the selecting points into a file when I click a button in the app.

I have tried the following code to add a button:

```
import numpy as np
import holoviews as hv
from holoviews.streams import Selection1D
from bokeh.models import Button
from bokeh.io import curdoc
from bokeh.layouts import layout

renderer = hv.renderer('bokeh')
hv.opts("Points [tools=['box_select']]")

data = np.random.multivariate_normal((0, 0), [[1, 0.1], [0.1, 1]], (1000,))
points = hv.Points(data)
sel = Selection1D(source=points)
mean_sel = hv.DynamicMap(lambda index: hv.HLine(points.iloc[index]['y'].mean()
                                                if index else -10),
                         kdims=[], streams=[sel])

# Convert the HoloViews object into a plot
plot = renderer.get_plot(points * mean_sel)

def save_index():
    np.save('select',sel.contents['index'])

button = Button(label='Save', width=60)
button.on_click(save_index)

# Combine the bokeh plot on plot.state with the widgets
lay = layout([
    [plot.state],
    [button],
], sizing_mode='fixed')

curdoc().add_root(layout)
```

But the following error occurs when I try to run the app:

```
Uncaught exception GET /simple_save (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/simple_save', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/bokeh/server/views/doc_handler.py", line 55, in get
    session = yield self.get_session()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/bokeh/application/application.py", line 183, in initialize_document
    doc.validate()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/bokeh/document/document.py", line 884, in validate
    refs = r.references()
AttributeError: 'function' object has no attribute 'references'
```

I wonder if there is a way to add a button that can save the indices of the selecting data?
Thanks in advance!

**Comment by philippjfr** [comment]
I'll close since this is a usage question. That said I couldn't reproduce any issues, I rewrote the app using [panel](http://panel.pyviz.org) which makes the integration a little easier and works in both notebook and bokeh server deployments:

```python
import numpy as np
import holoviews as hv
import panel as pn

from holoviews.streams import Selection1D

hv.extension('bokeh')
hv.opts("Points [tools=['box_select']]")

data = np.random.multivariate_normal((0, 0), [[1, 0.1], [0.1, 1]], (1000,))
points = hv.Points(data)
sel = Selection1D(source=points)
mean_sel = hv.DynamicMap(lambda index: hv.HLine(points.iloc[index]['y'].mean()
                                                if index else -10),
                         kdims=[], streams=[sel])

def save_index(event):
    np.save('select',sel.contents['index'])

button = pn.widgets.Button(name='Save', width=60)
button.param.watch(save_index, ['clicks']) 

pn.Column(points * mean_sel, button).servable()
```

**Comment by phonchi** [comment]
> I'll close since this is a usage question. That said I couldn't reproduce any issues, I rewrote the app using [panel](http://panel.pyviz.org) which makes the integration a little easier and works in both notebook and bokeh server deployments:
> 
> ```python
> import numpy as np
> import holoviews as hv
> import panel as pn
> 
> from holoviews.streams import Selection1D
> 
> hv.extension('bokeh')
> hv.opts("Points [tools=['box_select']]")
> 
> data = np.random.multivariate_normal((0, 0), [[1, 0.1], [0.1, 1]], (1000,))
> points = hv.Points(data)
> sel = Selection1D(source=points)
> mean_sel = hv.DynamicMap(lambda index: hv.HLine(points.iloc[index]['y'].mean()
>                                                 if index else -10),
>                          kdims=[], streams=[sel])
> 
> def save_index(event):
>     np.save('select',sel.contents['index'])
> 
> button = pn.widgets.Button(name='Save', width=60)
> button.param.watch(save_index, ['clicks']) 
> 
> pn.Column(points * mean_sel, button).servable()
> ```

Thanks! It seems that the panel is good at creating a custom app. I will look into it.
