### ISSUE TITLE
Linked selection cross-filtering breaks on dask dataframes

### ISSUE THREAD

**Issue by philippjfr** [pyviz/holoviews#4034]
It seems that in certain cases cross-filtering using the new linked selection utility fails on dask dataframes. I haven't yet looked into this deeply but it appears to happen when combining multiple selection expressions. Here's the error:

```
	Metadata inference failed in `and_`.
	
	Original error is below:
	------------------------
	ValueError('operands could not be broadcast together with shapes (2,) (304,) ')
	
	Traceback:
	---------
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 170, in raise_on_meta_error
	    yield
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/utils.py", line 1048, in partial_by_order
	    return function(*args2, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1321, in wrapper
	    res_values = na_op(self.values, ovalues)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1254, in na_op
	    result = op(x, y)
	
	Traceback (most recent call last):
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 170, in raise_on_meta_error
	    yield
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/utils.py", line 1048, in partial_by_order
	    return function(*args2, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1321, in wrapper
	    res_values = na_op(self.values, ovalues)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1254, in na_op
	    result = op(x, y)
	ValueError: operands could not be broadcast together with shapes (2,) (304,) 
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/plotting/util.py", line 273, in get_plot_frame
	    return map_obj[key]
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1324, in __getitem__
	    val = self._execute_callback(*tuple_key)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1097, in _execute_callback
	    retval = self.callback(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 700, in __call__
	    if not args and not kwargs and not any(kwarg_hash): return self.callable()
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/overlay.py", line 31, in dynamic_mul
	    element = other[args]
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1324, in __getitem__
	    val = self._execute_callback(*tuple_key)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1097, in _execute_callback
	    retval = self.callback(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 700, in __call__
	    if not args and not kwargs and not any(kwarg_hash): return self.callable()
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/util/__init__.py", line 940, in dynamic_operation
	    return self._process(map_obj[key], key, kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1324, in __getitem__
	    val = self._execute_callback(*tuple_key)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1097, in _execute_callback
	    retval = self.callback(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 700, in __call__
	    if not args and not kwargs and not any(kwarg_hash): return self.callable()
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 213, in dynamic_mul
	    other_el = other.select(HoloMap, **key_map) if other.kdims else other[()]
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1324, in __getitem__
	    val = self._execute_callback(*tuple_key)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1097, in _execute_callback
	    retval = self.callback(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 731, in __call__
	    ret = self.callable(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/util/__init__.py", line 940, in dynamic_operation
	    return self._process(map_obj[key], key, kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/util/__init__.py", line 923, in _process
	    return self.p.operation(element, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 308, in apply_map
	    clone=True,
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 202, in pipelined_fn
	    result = method_fn(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 1045, in map
	    return super(Dataset, self).map(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/dimension.py", line 704, in map
	    return map_fn(self) if applies else self
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 306, in <lambda>
	    lambda el: build_layer(el, colors, exprs),
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 349, in _build_layer
	    element, colors[layer_number], exprs[layer_number]
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/plotting/bokeh/selection.py", line 12, in _build_element_layer
	    element, visible = self._select(element, selection_expr)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 367, in _select
	    element.dataset.select(selection_expr=selection_expr)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 202, in pipelined_fn
	    result = method_fn(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 529, in select
	    mask = selection_expr.apply(self, compute=False, keep_index=True)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/util/transform.py", line 388, in apply
	    data = o['fn'](*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 1340, in <lambda>
	    return lambda self, other: elemwise(op, self, other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/contextlib.py", line 130, in __exit__
	    self.gen.throw(type, value, traceback)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 191, in raise_on_meta_error
	    raise ValueError(msg)
	ValueError: Metadata inference failed in `and_`.
	
	Original error is below:
	------------------------
	ValueError('operands could not be broadcast together with shapes (2,) (304,) ')
	
	Traceback:
	---------
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 170, in raise_on_meta_error
	    yield
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/utils.py", line 1048, in partial_by_order
	    return function(*args2, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1321, in wrapper
	    res_values = na_op(self.values, ovalues)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1254, in na_op
	    result = op(x, y)
	
	
	Metadata inference failed in `and_`.
	
	Original error is below:
	------------------------
	ValueError('operands could not be broadcast together with shapes (2,) (35338616,) ')
	
	Traceback:
	---------
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 170, in raise_on_meta_error
	    yield
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/utils.py", line 1048, in partial_by_order
	    return function(*args2, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1321, in wrapper
	    res_values = na_op(self.values, ovalues)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1254, in na_op
	    result = op(x, y)
	
	Traceback (most recent call last):
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 170, in raise_on_meta_error
	    yield
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/utils.py", line 1048, in partial_by_order
	    return function(*args2, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1321, in wrapper
	    res_values = na_op(self.values, ovalues)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1254, in na_op
	    result = op(x, y)
	ValueError: operands could not be broadcast together with shapes (2,) (35338616,) 
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/plotting/util.py", line 273, in get_plot_frame
	    return map_obj[key]
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1324, in __getitem__
	    val = self._execute_callback(*tuple_key)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1097, in _execute_callback
	    retval = self.callback(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 700, in __call__
	    if not args and not kwargs and not any(kwarg_hash): return self.callable()
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 213, in dynamic_mul
	    other_el = other.select(HoloMap, **key_map) if other.kdims else other[()]
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1324, in __getitem__
	    val = self._execute_callback(*tuple_key)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1097, in _execute_callback
	    retval = self.callback(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 731, in __call__
	    ret = self.callable(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/util/__init__.py", line 940, in dynamic_operation
	    return self._process(map_obj[key], key, kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/util/__init__.py", line 923, in _process
	    return self.p.operation(element, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 308, in apply_map
	    clone=True,
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 202, in pipelined_fn
	    result = method_fn(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 1045, in map
	    return super(Dataset, self).map(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/dimension.py", line 704, in map
	    return map_fn(self) if applies else self
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 306, in <lambda>
	    lambda el: build_layer(el, colors, exprs),
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 349, in _build_layer
	    element, colors[layer_number], exprs[layer_number]
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/plotting/bokeh/selection.py", line 12, in _build_element_layer
	    element, visible = self._select(element, selection_expr)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 367, in _select
	    element.dataset.select(selection_expr=selection_expr)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 202, in pipelined_fn
	    result = method_fn(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 529, in select
	    mask = selection_expr.apply(self, compute=False, keep_index=True)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/util/transform.py", line 388, in apply
	    data = o['fn'](*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 1340, in <lambda>
	    return lambda self, other: elemwise(op, self, other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/contextlib.py", line 130, in __exit__
	    self.gen.throw(type, value, traceback)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 191, in raise_on_meta_error
	    raise ValueError(msg)
	ValueError: Metadata inference failed in `and_`.
	
	Original error is below:
	------------------------
	ValueError('operands could not be broadcast together with shapes (2,) (35338616,) ')
	
	Traceback:
	---------
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 170, in raise_on_meta_error
	    yield
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/utils.py", line 1048, in partial_by_order
	    return function(*args2, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1321, in wrapper
	    res_values = na_op(self.values, ovalues)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1254, in na_op
	    result = op(x, y)
	
	
	Metadata inference failed in `and_`.
	
	Original error is below:
	------------------------
	ValueError('operands could not be broadcast together with shapes (2,) (35338616,) ')
	
	Traceback:
	---------
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 170, in raise_on_meta_error
	    yield
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/utils.py", line 1048, in partial_by_order
	    return function(*args2, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1321, in wrapper
	    res_values = na_op(self.values, ovalues)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1254, in na_op
	    result = op(x, y)
	
	Traceback (most recent call last):
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 170, in raise_on_meta_error
	    yield
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/utils.py", line 1048, in partial_by_order
	    return function(*args2, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1321, in wrapper
	    res_values = na_op(self.values, ovalues)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1254, in na_op
	    result = op(x, y)
	ValueError: operands could not be broadcast together with shapes (2,) (35338616,) 
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/plotting/util.py", line 273, in get_plot_frame
	    return map_obj[key]
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1324, in __getitem__
	    val = self._execute_callback(*tuple_key)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1097, in _execute_callback
	    retval = self.callback(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 700, in __call__
	    if not args and not kwargs and not any(kwarg_hash): return self.callable()
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 213, in dynamic_mul
	    other_el = other.select(HoloMap, **key_map) if other.kdims else other[()]
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1324, in __getitem__
	    val = self._execute_callback(*tuple_key)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 1097, in _execute_callback
	    retval = self.callback(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/spaces.py", line 731, in __call__
	    ret = self.callable(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/util/__init__.py", line 940, in dynamic_operation
	    return self._process(map_obj[key], key, kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/util/__init__.py", line 923, in _process
	    return self.p.operation(element, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 308, in apply_map
	    clone=True,
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 202, in pipelined_fn
	    result = method_fn(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 1045, in map
	    return super(Dataset, self).map(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/dimension.py", line 704, in map
	    return map_fn(self) if applies else self
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 306, in <lambda>
	    lambda el: build_layer(el, colors, exprs),
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 349, in _build_layer
	    element, colors[layer_number], exprs[layer_number]
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/plotting/bokeh/selection.py", line 12, in _build_element_layer
	    element, visible = self._select(element, selection_expr)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/selection.py", line 367, in _select
	    element.dataset.select(selection_expr=selection_expr)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 202, in pipelined_fn
	    result = method_fn(*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/core/data/__init__.py", line 529, in select
	    mask = selection_expr.apply(self, compute=False, keep_index=True)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/holoviews/util/transform.py", line 388, in apply
	    data = o['fn'](*args, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 1340, in <lambda>
	    return lambda self, other: elemwise(op, self, other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/contextlib.py", line 130, in __exit__
	    self.gen.throw(type, value, traceback)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 191, in raise_on_meta_error
	    raise ValueError(msg)
	ValueError: Metadata inference failed in `and_`.
	
	Original error is below:
	------------------------
	ValueError('operands could not be broadcast together with shapes (2,) (35338616,) ')
	
	Traceback:
	---------
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/utils.py", line 170, in raise_on_meta_error
	    yield
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/dataframe/core.py", line 4410, in elemwise
	    meta = partial_by_order(*parts, function=op, other=other)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/dask/utils.py", line 1048, in partial_by_order
	    return function(*args2, **kwargs)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1321, in wrapper
	    res_values = na_op(self.values, ovalues)
	  File "/Users/philippjfr/miniconda3/envs/flight-demo/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 1254, in na_op
	    result = op(x, y)
```
	
I'll try to investigate further at some point.

Cc: @jonmmease

**Comment by jonmmease** [comment]
Thanks for writing this up @philippjfr. I *think* the general problem here may be that the `dim` expression system doesn't have explicit dask support.  Some things work automatically when the dask objects have the same supported methods/operations, but I think we'll need to add some explicit support there.

**Comment by philippjfr** [comment]
Good point, it's probably not a perfect fix but as a starting point we could do something like this:

```python
fn = o['fn']
if is_dask(data) and fn is getattr(np, name, None):
    fn = getattr(da, fn.__name__, fn)
data = fn(*args, **kwargs)
```

**Comment by philippjfr** [comment]
Not actually sufficient to fix it sadly.

**Comment by jonmmease** [comment]
I'll take a look at adding `map_partitions`-based dask support today.

**Comment by philippjfr** [comment]
I was trying that. Unfortunately in my brief attempts I didn't find a solution that works generally. The main issue I had was that dim transforms can apply reductions or simple transforms and it's not really possible to do ahead of time.

**Comment by jonmmease** [comment]
Which part isn't possible to do ahead of time? Could you give an example?

**Comment by philippjfr** [comment]
I'm saying none of it can be done because you don't know what the transform is ahead of time.

**Comment by jonmmease** [comment]
Should be fixed in https://github.com/pyviz/holoviews/pull/4044
